/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.rameses.jobscheduler;

import com.rameses.common.ExpressionResolver;
import com.rameses.osiris2.themes.FormPage;
import com.rameses.rcp.ui.annotations.StyleSheet;
import com.rameses.rcp.ui.annotations.Template;

/**
 *
 * @author dell
 */
@Template(FormPage.class)
@StyleSheet
public class JobSchedulerForm extends javax.swing.JPanel {

    /**
     * Creates new form JobSchedulerForm
     */
    public JobSchedulerForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        xFormPanel1 = new com.rameses.rcp.control.XFormPanel();
        xTextField1 = new com.rameses.rcp.control.XTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        xTextArea1 = new com.rameses.rcp.control.XTextArea();
        xComboBox3 = new com.rameses.rcp.control.XComboBox();
        pnlCard = new javax.swing.JPanel();
        xPanel1 = new com.rameses.rcp.control.XPanel();
        xFormPanel5 = new com.rameses.rcp.control.XFormPanel();
        xFormPanel2 = new com.rameses.rcp.control.XFormPanel();
        xDateField1 = new com.rameses.rcp.control.XDateField();
        xMaskField1 = new com.rameses.rcp.control.XMaskField();
        xFormPanel6 = new com.rameses.rcp.control.XFormPanel();
        xDateField2 = new com.rameses.rcp.control.XDateField();
        xMaskField3 = new com.rameses.rcp.control.XMaskField();
        xFormPanel3 = new com.rameses.rcp.control.XFormPanel();
        xFormPanel10 = new com.rameses.rcp.control.XFormPanel();
        xComboBox5 = new com.rameses.rcp.control.XComboBox();
        xLabel1 = new com.rameses.rcp.control.XLabel();
        xIntegerField4 = new com.rameses.rcp.control.XIntegerField();
        xLabel2 = new com.rameses.rcp.control.XLabel();
        xLabel5 = new com.rameses.rcp.control.XLabel();
        xFormPanel11 = new com.rameses.rcp.control.XFormPanel();
        xComboBox6 = new com.rameses.rcp.control.XComboBox();
        xLabel3 = new com.rameses.rcp.control.XLabel();
        xIntegerField5 = new com.rameses.rcp.control.XIntegerField();
        xLabel4 = new com.rameses.rcp.control.XLabel();
        xPanel2 = new com.rameses.rcp.control.XPanel();
        xFormPanel7 = new com.rameses.rcp.control.XFormPanel();
        xFormPanel8 = new com.rameses.rcp.control.XFormPanel();
        xDateField3 = new com.rameses.rcp.control.XDateField();
        xMaskField4 = new com.rameses.rcp.control.XMaskField();
        jPanel2 = new javax.swing.JPanel();
        xSubFormPanel1 = new com.rameses.rcp.control.XSubFormPanel();
        xActionBar1 = new com.rameses.rcp.control.XActionBar();

        xFormPanel1.setCaptionWidth(100);

        xTextField1.setCaption("Job Name");
        xTextField1.setName("entity.name"); // NOI18N
        xTextField1.setPreferredSize(new java.awt.Dimension(0, 20));
        xTextField1.setRequired(true);
        xFormPanel1.add(xTextField1);

        jScrollPane1.setPreferredSize(new java.awt.Dimension(0, 40));

        xTextArea1.setCaption("Description");
        xTextArea1.setName("entity.description"); // NOI18N
        xTextArea1.setPreferredSize(new java.awt.Dimension(0, 61));
        jScrollPane1.setViewportView(xTextArea1);

        xFormPanel1.add(jScrollPane1);

        xComboBox3.setAllowNull(false);
        xComboBox3.setCaption("Schedule Type");
        xComboBox3.setItems("scheduleTypeList");
        xComboBox3.setName("entity.scheduletype"); // NOI18N
        xFormPanel1.add(xComboBox3);

        pnlCard.setLayout(new java.awt.CardLayout());

        xPanel1.setDepends(new String[] {"entity.scheduletype"});
        xPanel1.setVisibleWhen("#{entity.scheduletype == 'recurring'}");

        xFormPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Daily Schedule", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        xFormPanel5.setCaptionWidth(100);

        xFormPanel2.setCaption("Start Date");
        xFormPanel2.setOrientation(com.rameses.rcp.constant.UIConstants.HORIZONTAL);
        xFormPanel2.setPadding(new java.awt.Insets(0, 0, 0, 0));

        xDateField1.setName("entity.startdate"); // NOI18N
        xDateField1.setRequired(true);
        xDateField1.setShowCaption(false);
        xFormPanel2.add(xDateField1);

        xMaskField1.setCaption("Start Time");
        xMaskField1.setCaptionWidth(80);
        xMaskField1.setCellPadding(new java.awt.Insets(0, 20, 0, 0));
        xMaskField1.setMask("##:##");
        xMaskField1.setName("entity.starttime"); // NOI18N
        xMaskField1.setPreferredSize(new java.awt.Dimension(40, 20));
        xMaskField1.setRequired(true);
        xFormPanel2.add(xMaskField1);

        xFormPanel5.add(xFormPanel2);

        xFormPanel6.setCaption("End Date");
        xFormPanel6.setOrientation(com.rameses.rcp.constant.UIConstants.HORIZONTAL);
        xFormPanel6.setPadding(new java.awt.Insets(0, 0, 0, 0));

        xDateField2.setName("entity.enddate"); // NOI18N
        xDateField2.setShowCaption(false);
        xFormPanel6.add(xDateField2);

        xMaskField3.setCaption("End Time");
        xMaskField3.setCaptionWidth(80);
        xMaskField3.setCellPadding(new java.awt.Insets(0, 20, 0, 0));
        xMaskField3.setMask("##:##");
        xMaskField3.setName("entity.endtime"); // NOI18N
        xMaskField3.setPreferredSize(new java.awt.Dimension(40, 20));
        xFormPanel6.add(xMaskField3);

        xFormPanel5.add(xFormPanel6);

        xFormPanel3.setCaptionWidth(100);

        xFormPanel10.setCaption("Frequency");
        xFormPanel10.setCaptionWidth(120);
        xFormPanel10.setCellspacing(0);
        xFormPanel10.setOrientation(com.rameses.rcp.constant.UIConstants.HORIZONTAL);
        xFormPanel10.setPadding(new java.awt.Insets(0, 0, 0, 0));

        xComboBox5.setAllowNull(false);
        xComboBox5.setCaption("Daily Recurrence");
        xComboBox5.setDepends(new String[] {"entity.scheduletype"});
        xComboBox5.setExpression("#{item.type}");
        xComboBox5.setItems("frequencyTypeList");
        xComboBox5.setName("frequencytype"); // NOI18N
        xComboBox5.setShowCaption(false);
        xFormPanel10.add(xComboBox5);

        xLabel1.setCellPadding(new java.awt.Insets(0, 20, 0, 0));
        xLabel1.setDepends(new String[] {"entity.frequencytype"});
        xLabel1.setExpression("Every");
        xLabel1.setPreferredSize(new java.awt.Dimension(41, 20));
        xLabel1.setShowCaption(false);
        xFormPanel10.add(xLabel1);

        xIntegerField4.setCaption("every");
        xIntegerField4.setDepends(new String[] {"frequencytype"});
        xIntegerField4.setName("entity.frequencyinterval"); // NOI18N
        xIntegerField4.setPreferredSize(new java.awt.Dimension(40, 20));
        xIntegerField4.setRequired(true);
        xIntegerField4.setShowCaption(false);
        xFormPanel10.add(xIntegerField4);

        xLabel2.setDepends(new String[] {"frequencytype"});
        xLabel2.setExpression("#{frequencytype.expr}");
        xLabel2.setPreferredSize(new java.awt.Dimension(80, 20));
        xLabel2.setShowCaption(false);
        xFormPanel10.add(xLabel2);

        xFormPanel3.add(xFormPanel10);

        xLabel5.setPreferredSize(new java.awt.Dimension(4, 10));
        xLabel5.setShowCaption(false);
        xFormPanel3.add(xLabel5);

        xFormPanel11.setCaption("Daily Recurrence");
        xFormPanel11.setCaptionWidth(120);
        xFormPanel11.setCellspacing(0);
        xFormPanel11.setOrientation(com.rameses.rcp.constant.UIConstants.HORIZONTAL);
        xFormPanel11.setPadding(new java.awt.Insets(0, 0, 0, 0));

        xComboBox6.setAllowNull(false);
        xComboBox6.setCaption("Daily Recurrence");
        xComboBox6.setExpression("#{item.type}");
        xComboBox6.setItems("recurTypeList");
        xComboBox6.setName("recurtype"); // NOI18N
        xComboBox6.setShowCaption(false);
        xFormPanel11.add(xComboBox6);

        xLabel3.setCellPadding(new java.awt.Insets(0, 20, 0, 0));
        xLabel3.setDepends(new String[] {"recurtype"});
        xLabel3.setExpression("Every");
        xLabel3.setName("recurexpr"); // NOI18N
        xLabel3.setPreferredSize(new java.awt.Dimension(41, 20));
        xLabel3.setShowCaption(false);
        xFormPanel11.add(xLabel3);

        xIntegerField5.setCaption("every");
        xIntegerField5.setDepends(new String[] {"recurtype"});
        xIntegerField5.setName("entity.recurinterval"); // NOI18N
        xIntegerField5.setPreferredSize(new java.awt.Dimension(40, 20));
        xIntegerField5.setRequired(true);
        xIntegerField5.setShowCaption(false);
        xFormPanel11.add(xIntegerField5);

        xLabel4.setDepends(new String[] {"recurtype"});
        xLabel4.setExpression("#{recurtype.expr}");
        xLabel4.setName("recurexpr"); // NOI18N
        xLabel4.setPreferredSize(new java.awt.Dimension(80, 20));
        xLabel4.setShowCaption(false);
        xFormPanel11.add(xLabel4);

        xFormPanel3.add(xFormPanel11);

        javax.swing.GroupLayout xPanel1Layout = new javax.swing.GroupLayout(xPanel1);
        xPanel1.setLayout(xPanel1Layout);
        xPanel1Layout.setHorizontalGroup(
            xPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(xPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(xPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(xPanel1Layout.createSequentialGroup()
                        .addComponent(xFormPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(xPanel1Layout.createSequentialGroup()
                        .addComponent(xFormPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(241, 241, 241))))
        );
        xPanel1Layout.setVerticalGroup(
            xPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(xPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(xFormPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(xFormPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pnlCard.add(xPanel1, "card3");

        xPanel2.setDepends(new String[] {"entity.scheduletype"});
        xPanel2.setVisibleWhen("#{entity.scheduletype == 'once'}");

        xFormPanel7.setBorder(null);
        xFormPanel7.setCaptionWidth(100);

        xFormPanel8.setCaption("Start Date");
        xFormPanel8.setOrientation(com.rameses.rcp.constant.UIConstants.HORIZONTAL);
        xFormPanel8.setPadding(new java.awt.Insets(0, 0, 0, 0));

        xDateField3.setName("entity.startdate"); // NOI18N
        xDateField3.setRequired(true);
        xDateField3.setShowCaption(false);
        xFormPanel8.add(xDateField3);

        xMaskField4.setCaption("Start Time");
        xMaskField4.setCaptionWidth(80);
        xMaskField4.setCellPadding(new java.awt.Insets(0, 20, 0, 0));
        xMaskField4.setMask("##:##");
        xMaskField4.setName("entity.starttime"); // NOI18N
        xMaskField4.setPreferredSize(new java.awt.Dimension(40, 20));
        xMaskField4.setRequired(true);
        xFormPanel8.add(xMaskField4);

        xFormPanel7.add(xFormPanel8);

        javax.swing.GroupLayout xPanel2Layout = new javax.swing.GroupLayout(xPanel2);
        xPanel2.setLayout(xPanel2Layout);
        xPanel2Layout.setHorizontalGroup(
            xPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(xPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(xFormPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(104, Short.MAX_VALUE))
        );
        xPanel2Layout.setVerticalGroup(
            xPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(xPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(xFormPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(117, Short.MAX_VALUE))
        );

        pnlCard.add(xPanel2, "card3");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(xFormPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlCard, javax.swing.GroupLayout.DEFAULT_SIZE, 512, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(xFormPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlCard, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(432, 432, 432))
        );

        jTabbedPane1.addTab("General", jPanel1);

        xSubFormPanel1.setDynamic(true);
        xSubFormPanel1.setHandler("actionOpener");

        javax.swing.GroupLayout xSubFormPanel1Layout = new javax.swing.GroupLayout(xSubFormPanel1);
        xSubFormPanel1.setLayout(xSubFormPanel1Layout);
        xSubFormPanel1Layout.setHorizontalGroup(
            xSubFormPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 512, Short.MAX_VALUE)
        );
        xSubFormPanel1Layout.setVerticalGroup(
            xSubFormPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 290, Short.MAX_VALUE)
        );

        xActionBar1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        xActionBar1.setName("actionList"); // NOI18N
        xActionBar1.setUseToolBar(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(xSubFormPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 512, Short.MAX_VALUE)
                    .addComponent(xActionBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(xActionBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(xSubFormPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Action", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel pnlCard;
    private com.rameses.rcp.control.XActionBar xActionBar1;
    private com.rameses.rcp.control.XComboBox xComboBox3;
    private com.rameses.rcp.control.XComboBox xComboBox5;
    private com.rameses.rcp.control.XComboBox xComboBox6;
    private com.rameses.rcp.control.XDateField xDateField1;
    private com.rameses.rcp.control.XDateField xDateField2;
    private com.rameses.rcp.control.XDateField xDateField3;
    private com.rameses.rcp.control.XFormPanel xFormPanel1;
    private com.rameses.rcp.control.XFormPanel xFormPanel10;
    private com.rameses.rcp.control.XFormPanel xFormPanel11;
    private com.rameses.rcp.control.XFormPanel xFormPanel2;
    private com.rameses.rcp.control.XFormPanel xFormPanel3;
    private com.rameses.rcp.control.XFormPanel xFormPanel5;
    private com.rameses.rcp.control.XFormPanel xFormPanel6;
    private com.rameses.rcp.control.XFormPanel xFormPanel7;
    private com.rameses.rcp.control.XFormPanel xFormPanel8;
    private com.rameses.rcp.control.XIntegerField xIntegerField4;
    private com.rameses.rcp.control.XIntegerField xIntegerField5;
    private com.rameses.rcp.control.XLabel xLabel1;
    private com.rameses.rcp.control.XLabel xLabel2;
    private com.rameses.rcp.control.XLabel xLabel3;
    private com.rameses.rcp.control.XLabel xLabel4;
    private com.rameses.rcp.control.XLabel xLabel5;
    private com.rameses.rcp.control.XMaskField xMaskField1;
    private com.rameses.rcp.control.XMaskField xMaskField3;
    private com.rameses.rcp.control.XMaskField xMaskField4;
    private com.rameses.rcp.control.XPanel xPanel1;
    private com.rameses.rcp.control.XPanel xPanel2;
    private com.rameses.rcp.control.XSubFormPanel xSubFormPanel1;
    private com.rameses.rcp.control.XTextArea xTextArea1;
    private com.rameses.rcp.control.XTextField xTextField1;
    // End of variables declaration//GEN-END:variables
}
